AWSTemplateFormatVersion: 2010-09-09
Description: ECR template

Parameters:
  System:
    Type: String
    Default: ecs-handson

Resources:
# ------------------------------------------------------------#
# ECR 
# ------------------------------------------------------------# 
  ECR:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Sub ${System}-ecr
      EmptyOnDelete: false
      EncryptionConfiguration:
        EncryptionType: KMS
      ImageScanningConfiguration:
        ScanOnPush: true