AWSTemplateFormatVersion: "2010-09-09"
Description: Endpoint template

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
# ------------------------------------------------------------#
# VPC Endpoint
# ------------------------------------------------------------# 
  CloudwatchLogsVPCEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      SubnetIds: 
        - !Ref SubnetId 
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref SecurityGroupId
          
  CloudwatchMonitoringEC2VPCEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.monitoring"
      SubnetIds: 
        - !Ref SubnetId 
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref SecurityGroupId