AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 template

Parameters:
  System:
    Type: String
    Default: ec2-handson

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
# ------------------------------------------------------------#
# EC2 IAM Role
# ------------------------------------------------------------# 
  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${System}-ssm-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        
# ------------------------------------------------------------#
# EC2 Instance Profile
# ------------------------------------------------------------# 
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: EC2IAMRole
      InstanceProfileName: !Sub ${System}-ec2-instance-profile
      
# ------------------------------------------------------------#
# EC2 Instance
# ------------------------------------------------------------#       
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c6359fd9eb30edcf # ap-northeast-1 Amazon Linux 2023 AMI ID, different in each region
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: !Sub ${System}-ec2